[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "philosophy"
    name = "Philosophy"
    url = "/philosophy"
    weight = 2
 
[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 3
    
# Social Media Configuration

[[social]]
    identifier = "email"
    name = "E-mail"
    url = "mailto:hi@mhef.com.br"
    weight = 1

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://linkedin.com/in/mhf"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/mhef"
    weight = 3